version: '3.9'
services:
  front:
    image: deerr1/pinproject_front
    build: pin-front
    # comand: run serve
    # volumes:
    #   - ./pin-front:/app/front
    ports:
      - 8082:5001
  back:
    image: deerr1/pinproject_back
    build: pin-back
    command: bash -c "python3 manage.py migrate
            && python3 manage.py runserver 0.0.0.0:5000"
    # volumes:
    #   - ./pin-back:/app/back
    ports:
      - 8081:5000
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pin
    ports:
      - 5432:5432
