version: '3.9'
services:
  front:
    image: leekpuh/front:0.1
    container_name: front
    ports:
      - 8082:5001
  back:
    image: leekpuh/back:0.1
    container_name: back
    command: bash -c "python3 manage.py migrate
            && python3 manage.py runserver 0.0.0.0:5000"
    ports:
      - 8081:5000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
